package sim6502

// ProcessorOption defines options that can be used to influence
// the behavior of the processor
// Hint: setting some of these options via breakpoint handlers can be useful for debugging
type ProcessorOption int

const (
	// ErrorOnSelfJump option, when activated, will cause an error to be generated by the processor
	// if a branch or JMP instruction redirects back to itself
	// This is useful for testing scenarios
	ErrorOnSelfJump ProcessorOption = iota

	// Trace option will cause output of a single line of debug for every instructions (pre-execution)
	Trace

	// TraceStack option will cause the stack to be dumped prior to every operation
	TraceStack

	// TraceInterrupts will cause messages to be printed when external interrupts are triggered
	TraceInterrupts

	// ErrorOnJAM will cause an error to be generated if an (illegal) JAM is enconutered
	// with the illegal instruction set enabled
	// if this is not set, then the processor will just lock up
	ErrorOnJAM

	// AutoResetIRQ will cause the IRQ line to be forcefully unasserted when the IRQ
	// branch is taken
	AutoResetIRQ

	// AutoRsetNMI will cause the NMI line to be forcefully unasserted when the NMI
	// branch is taken
	AutoResetNMI

	// Fix6502BrokenJMP will fix the incorrect behavior of indirect JUMP on 6502 (not 65C02 which is not broken)
	// The (implemented) broken behavior is to jump to the address stored at xxff (L), xx00 (H) instead of
	// xxff (L), xx+100 (H)
	Fix6052BrokenJMP
)
